# Generated by Django 4.0.3 on 2022-03-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=100, verbose_name='Тип услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_work', models.PositiveIntegerField(verbose_name='время работ в днях')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('type_of_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tga.typeofservice', verbose_name='Тип услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegtam', models.PositiveIntegerField(unique=True, verbose_name='id клиента')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя клиента')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия клиента')),
                ('customer', models.BooleanField(verbose_name='является ли клиент заказчиком')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Услуги', to='tga.service')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
