# Generated by Django 4.0.3 on 2022-03-06 12:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegtam', models.PositiveIntegerField(unique=True, verbose_name='id клиента')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя клиента')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия клиента')),
                ('master', models.BooleanField(verbose_name='является ли клиент мастером')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=100, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Тип услуги',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_work', models.PositiveIntegerField(verbose_name='время работ в днях')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('description', models.TextField(default='Кратко об услуге', verbose_name='Описание услуги')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Услуги', to='tga.client', verbose_name='Имя клиента')),
                ('type_of_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tga.typeofservice', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Предоставляемая услуга',
                'verbose_name_plural': 'Предоставляемые услуги',
            },
        ),
    ]
