# Generated by Django 4.0.3 on 2022-03-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0003_alter_client_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Кратко об услуге', verbose_name='Описание услуги'),
        ),
    ]
