# Generated by Django 4.0.3 on 2022-03-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0004_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Услуги', to='tga.client', verbose_name='Имя клиента'),
        ),
    ]
