# Generated by Django 4.0.3 on 2022-03-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0005_remove_client_service_service_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='master',
        ),
    ]
