# Generated by Django 4.0.3 on 2022-03-03 14:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tga', '0006_rename_service_service_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='customer',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='номер телефона'),
        ),
    ]
